.github/dependabot.yml, .github/workflows/codeql.yml, Boyfriend/Boyfriend.cs, Boyfriend/Boyfriend.csproj, Boyfriend/CommandProcessor.cs, Boyfriend/Commands/MuteCommand.cs, Boyfriend/Commands/SettingsCommand.cs, Boyfriend/Commands/UnmuteCommand.cs, Boyfriend/Utils.cs
This PR adds a Dependabot configuration to automatically submit pull requests for bumping dependencies and sets up an Action for CodeQL build and scan
=> Improve code quality and security

Boyfriend/Boyfriend.cs
There can now be more than 1 Activity (status message) for the bot! They are now present in a List that contains the song names and durations
=> Added support for multiple Activities

Boyfriend/Boyfriend.cs, Boyfriend/EventHandler.cs, Boyfriend/Messages.Designer.cs, Boyfriend/Messages.resx, Boyfriend/Messages.ru.resx, Boyfriend/Messages.tt-ru.resx, Boyfriend/Utils.cs
totally didn't take 2 painful days
=> Added early event start notifications

src/Commands/ClearCommandGroup.cs
Depends on #54
This PR reduces the method complexity of `ClearCommandGroup#ClearMessagesAsync` by doing the following:
- Splitting the command method into 2 parts: ExecuteClear and ClearMessagesAsync. The former will check all the needed results and will pass the outputs into the latter;
- Using the recently extracted method `UtilityService#LogActionAsync` to log deletion of messages.
=> Reduce method complexity of /clear

docs/README.md
=> Remove "code quality" badge

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/SettingsCommandGroup.cs, src/Data/Options/BoolOption.cs, src/Messages.Designer.cs
This PR is mainly aimed at improving /settingslist and fixing /settings
List of things to do before merging:
And since the development has already been taking more than 2 days, I suggest splitting the PR into 2 parts.
List of other things that will be in the future PR:
- mctaylors#1
- Fix bot not answering when an invalid setting is specified in /settings
- Options list for /settings
=> Improved /settingslist + fixed /settings pt.1

src/Services/GuildUpdateService.cs
This PR adds some soundtracks from five different games to the bot's listening activity.
List of soundtracks added:
- Jukio Kallio, Daniel Hagström - Fall 'n' Roll (Fall Guys)
- SCATTLE - Hypertension (Super Meat Boy)
- KEYGEN CHURCH - Tenebre Rosso Sangue (ULTRAKILL)
- Chipzel - Swing Me Another 6 (Dicey Dungeons)
- ~Floex - The Glasshouse With Butterfly (Machinarium)~
- Noisecream - Mist of Rage (My Friend Pedro)
=> Add soundtracks from different games

src/Commands/SettingsCommandGroup.cs
This PR makes the bot log guild settings to the Private Feedback Channel. The functionality was present in pre-Remora Boyfriend, but was missing afterwards, so I will call this a bug, making this PR a bugfix.
cc @mctaylors - embed design needs review
=> Log guild setting changes to PrivateFeedbackChannel

.github/CODEOWNERS, Boyfriend.csproj, docs/CONTRIBUTING.md, docs/README.md, src/Commands/AboutCommandGroup.cs
we are moving!
(6 commits because I was too lazy to open the IDE)
=> Change organization name references from TeamOctolings to LabsDevelopment

.github/workflows/build-push.yml
The production environment and host are ready for this PR
=> Allow better customisation of autodeploy through secrets and variables

src/Services/Update/SongUpdateService.cs
Music added:
- EDWXRDX - CONSCIENCE (2:16)
- dontleaveme - afterward (2:29)
- Clams Casino - I'm God (4:37)
- Jupyter - Starboy (2:35)
- VØJ, Narvent - Memory Reboot (3:29)
Timecode source: [Yandex.Music](https://music.yandex.ru)
=> Add MORE music to the bot

src/Services/GuildDataService.cs
=> Disable the logging of `SaveAsync` due to spam in the logs

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/SettingsCommandGroup.cs, src/Data/Options/IOption.cs, src/Data/Options/Option.cs, src/Messages.Designer.cs, src/Services/GuildDataService.cs
I also disabled the logging of `SaveAsync` due to spam in the logs
=> Add /resetsettings

src/Commands/BanCommandGroup.cs
Please keep `MemberData` clean of unnecessary values.
=> Set MemberData.BannedUntil to null in /unban

src/Services/GuildDataService.cs
=> Skip refreshing roles if the member is role-muted

src/Responders/GuildMemberJoinedResponder.cs
=> Fix mute role returning when rejoining server

src/Services/Update/SongUpdateService.cs
- Deep Cut - Big Betrayal — [source](https://www.youtube.com/watch?v=BMy7gvl3bXE)
- Squid Sisters - Tommorrow's Nostalgia Today — [source](https://www.youtube.com/watch?v=S8VYi2ODeF4)
- Deep Cut - Anarchy Rainbow — [source](https://www.youtube.com/watch?v=DtMOAvOWTvY)
- Squid Sisters - Liquid Sunshine — [source](https://www.youtube.com/watch?v=EZx61kSObTIg)
- Damp Socks feat. Off the Hook - Candy-Coated Rocks — [source](https://youtube.com/watch?v=_-nyDSANZt4)
- H2Whoa - Aquasonic — [source](https://www.youtube.com/watch?v=t2sNgpFgFC0)
- Yoko & the Gold Bazookas - Ska-Blam! — [source](https://www.youtube.com/watch?v=9pHIwuTHcbc)
=> Add some Splatoon™ songs that I liked

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/AboutCommandGroup.cs, src/Commands/BanCommandGroup.cs, src/Commands/KickCommandGroup.cs, src/Commands/MuteCommandGroup.cs, src/Commands/RemindCommandGroup.cs, src/Extensions.cs, src/Messages.Designer.cs, src/Responders/MessageDeletedResponder.cs, src/Responders/MessageEditedResponder.cs
=> Redesign embeds

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/ToolsCommandGroup.cs, src/Messages.Designer.cs
It could have been a milestone PR, but of course I made a mistake _somewhere_.
=> Add /random

src/Services/Update/SongUpdateService.cs
I added a ~StringBuilder~ string interpolation for SongUpdateService for better activity status configuration. So now you can add some characters if you want, or even swap the song title and author.
Also songs are now displaying in Splatoon™ style.
=> Add string interpolation for SongUpdateService

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/ToolsCommandGroup.cs, src/Messages.Designer.cs
Original idea from @Octol1ttle
=> Add /timestamp

src/Commands/MuteCommandGroup.cs
=> Fix /unmute not checking if the target is muted

src/Responders/GuildLoadedResponder.cs
=> Edit log output in GuildLoadedResponder

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/ToolsCommandGroup.cs, src/Messages.Designer.cs
=> Rename /showinfo to avoid confusion with /guildinfo

src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes an error that would occur if an event was created, was about to start or started and the EventNotificationChannel was empty.
=> Do not try to send messages in empty EventNotificationChannels

src/Octobot.cs
This PR disables text commands as their presence was not intentional.
=> Disable text commands

src/Responders/GuildLoadedResponder.cs, src/Services/Update/MemberUpdateService.cs, src/Services/UtilityService.cs
This PR fixes an issue that caused REST errors to occur in MemberUpdateService if the bot tries to interact with a member it can't interact with. The issue is fixed by returning from TickMemberDataAsync early if the member cannot be interacted with. An error message was planned, but it requires adding a lot of services and severely increasing the complexity. Contributors may feel free to add one if they deem so necessary.
=> Check interactions in MemberUpdateService before operating on members

src/Responders/GuildLoadedResponder.cs
This PR adds additional information in the log about guilds as they are being loaded. The new information is the owner tag & ID and member count
=> Add more information to guild loaded log message

.github/dependabot.yml
=> Combine Dependabot PRs updating Remora.Discord packages into one

src/Services/Update/SongUpdateService.cs
Changes:
- Use timestamps from [Splatunes](https://splatoonwiki.org/wiki/Splatune_(Splatoon_Original_Soundtrack))
- Make 20 tracks in bot's playlist
- Replace Calamari Inkantation 3MIX by Calamari Inkantation due to long duration
=> Rewrite music list

docs/README.md
completely forgot about this while making #207
=> Recommend to install .NET 8 in README.md

src/Commands/AboutCommandGroup.cs, src/Commands/BanCommandGroup.cs, src/Commands/ClearCommandGroup.cs, src/Commands/Events/ErrorLoggingPostExecutionEvent.cs, src/Commands/KickCommandGroup.cs, src/Commands/MuteCommandGroup.cs, src/Commands/PingCommandGroup.cs, src/Commands/RemindCommandGroup.cs, src/Commands/SettingsCommandGroup.cs, src/Commands/ToolsCommandGroup.cs, src/Extensions/FeedbackServiceExtensions.cs
=> FeedbackServiceExtensions: Add options support

src/Commands/BanCommandGroup.cs, src/Commands/KickCommandGroup.cs, src/Extensions/ChannelApiExtensions.cs, src/Responders/GuildLoadedResponder.cs, src/Responders/GuildMemberJoinedResponder.cs, src/Responders/MessageDeletedResponder.cs, src/Responders/MessageEditedResponder.cs, src/Services/Update/MemberUpdateService.cs, src/Services/Update/ScheduledEventUpdateService.cs, src/Services/UtilityService.cs
In this PR, I added ChannelApiExtensions to make it easier to return Result from CreateMessageAsync
=> Add ChannelApiExtensions

src/Octobot.cs
now we don't have to explicitly type out command groups woooo
=> Use AddFromAssembly for responders and command groups

src/Commands/BanCommandGroup.cs
https://github.com/TeamOctolings/Octobot/issues/246#issuecomment-1912579699
> The `Option` attribute also somehow affects the command update behavior. I'll get rid of it then.
Closes #246
=> Don't use Option attribute in ExecuteBanAsync method

src/Commands/SettingsCommandGroup.cs, src/Commands/ToolsCommandGroup.cs
=> Profile ToolsCommandGroup

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/ToolsCommandGroup.cs, src/Messages.Designer.cs
@neroduckale was bored so I made this feature.
=> Add /8ball command

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/SettingsCommandGroup.cs, src/Data/GuildSettings.cs, src/Data/Options/AllOptionsEnum.cs, src/Messages.Designer.cs, src/Responders/GuildMemberJoinedResponder.cs
=> Add WelcomeMessagesChannel setting

src/Services/Update/MemberUpdateService.cs
=> Fix auto-unban log spam

Octobot.csproj, locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/BuildInfo.cs, src/Commands/AboutCommandGroup.cs, src/Commands/Events/ErrorLoggingPostExecutionEvent.cs, src/Messages.Designer.cs, src/Octobot.cs, src/Responders/GuildLoadedResponder.cs
In this PR, I added a NuGet package called GitInfo. It can replace Octobot.RepositoryUrl and display the bot version as the current branch and commit.
=> Add GitInfo NuGet package

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/Commands/PingCommandGroup.cs, src/Messages.Designer.cs, src/Responders/GuildLoadedResponder.cs
=> Fix /ping not showing correct locale

src/Commands/Events/ErrorLoggingPostExecutionEvent.cs, src/Commands/Events/LoggingPreparationErrorEvent.cs, src/Commands/MuteCommandGroup.cs, src/Data/Options/BoolOption.cs, src/Data/Options/Option.cs, src/Data/Options/SnowflakeOption.cs, src/Data/Options/TimeSpanOption.cs, src/Extensions/CollectionExtensions.cs, src/Extensions/GuildScheduledEventExtensions.cs, src/Responders/GuildLoadedResponder.cs, src/Responders/GuildMemberJoinedResponder.cs, src/Responders/GuildMemberLeftResponder.cs, src/Responders/GuildUnloadedResponder.cs, src/Responders/MessageDeletedResponder.cs, src/Responders/MessageEditedResponder.cs, src/Responders/MessageReceivedResponder.cs, src/Services/Update/MemberUpdateService.cs, src/Services/Update/ScheduledEventUpdateService.cs
See https://github.com/Remora/Remora.Results/pull/14
=> Use Result.Success property instead of Result.FromSuccess()

locale/Messages.resx, locale/Messages.ru.resx, locale/Messages.tt-ru.resx, src/BuildInfo.cs, src/Commands/AboutCommandGroup.cs, src/Commands/SettingsCommandGroup.cs, src/Commands/ToolsCommandGroup.cs, src/Messages.Designer.cs
This PR has been opened to finally update Octobot's Wiki.
Current changes summary:
- correct minor spelling issues in some command descriptions
- /about: add Octobot's Wiki button
=> Pre-Wiki Update

src/Commands/ClearCommandGroup.cs
This change makes Octobot split the message clear log into multiple messages when the combined length of cleared messages exceeds the maximum length for an embed description.
Closes #180
=> Split message clear log when cleared messages are too long

src/Services/AccessControlService.cs
=> Fix "No operation context has been set for this scope." crash on startup

TeamOctolings.Octobot/Commands/ClearCommandGroup.cs
Closes #314
What? The title speaks for itself.
=> Add description to /clear's author to clarify its functionality

.github/workflows/build-pr.yml
=> Bump InspectCode from 1.11.10 to 1.11.12

TeamOctolings.Octobot/Commands/AboutCommandGroup.cs, TeamOctolings.Octobot/Commands/BanCommandGroup.cs, TeamOctolings.Octobot/Commands/ClearCommandGroup.cs, TeamOctolings.Octobot/Commands/Events/ErrorLoggingPostExecutionEvent.cs, TeamOctolings.Octobot/Commands/KickCommandGroup.cs, TeamOctolings.Octobot/Commands/MuteCommandGroup.cs, TeamOctolings.Octobot/Data/Reminder.cs, TeamOctolings.Octobot/Responders/GuildLoadedResponder.cs, TeamOctolings.Octobot/Services/Update/ScheduledEventUpdateService.cs
Rider and R# 2024.2 have introduced new inspections, causing current builds to fail. This PR applies fixes for issues caught by these inspections.
=> Apply new inspection fixes

.github/workflows/build-push.yml
The key used for deploy is Ed25519, not RSA
=> Fix wrong private key file name

TeamOctolings.Octobot/Services/Update/SongUpdateService.cs
This PR fixes failing checks for #332
=> Fix redundant type specification

.github/workflows/build-push.yml
=> fix: lol, lmao, LMFAO even

.github/workflows/build-pr.yml, Dockerfile, TeamOctolings.Octobot/TeamOctolings.Octobot.csproj
Simple and self-explanatory.
Closes #342
=> Bump TargetFramework from 8.0 to 9.0
