- src/Commands/AboutCommandGroup.cs
- src/Commands/PingCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
This PR prevents usage of `/about`, `/ping` and `/remind` inside DMs. While it may look like these commands do not require a guild attached to them, the language system depends on having a guild to fetch settings from, so it is not possible to use these commands in DMs.
> Do not allow certain commands to be used in DMs

- .github/labels.yml
This PR adds a `labels.yml` file to configure the `pull-request-size` bot. The new thresholds are:
- 0-9 lines for XS
- 10-49 lines for S
- 50-99 lines for M
- 100-499 lines for L
- 500-999 lines for XL
- \>1000 for XXL
In the file, these thresholds are doubled to accomodate for the fact that both additions and deletions are counted (e.g. editing 10 lines will result in 10 additions and 10 deletions, 20 in total)
> Increase thresholds for size labels

- src/Boyfriend.cs
- src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
- src/Commands/Events/LoggingPreparationErrorEvent.cs
This PR splits `LoggingPreparationErrorEvent` and `ErrorLoggingPostExecutionEvent` classes into separate files and puts these files in a separate namespace: `Boyfriend.Commands.Events`. This makes these classes easier to find and distinguish from commands groups.
> Split error logging events into separate files

- src/Commands/AboutCommandGroup.cs
- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/PingCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Extensions.cs
- src/Services/UtilityService.cs
This PR does numerous things to reduce method complexity:
- Created an extension method `FeedbackService#SendContextualEmbedResultAsync`, which directly takes a `Result<Embed>` and checks it once in the extension method instead of multiple times in all commands;
- Split the command methods for `/ban` and `/unban` into 2 parts: `Execute(Un)Ban` and `(Un)BanUserAsync`. The former will check all the needed results and will pass the outputs into the latter;
- Extracted the method for logging an action into Private- and PublicFeedbackChannels. It now resides in UtilityService. Right now, only `/ban` and `/unban` make use of that method;
- Created an extension method `Snowflake#EmptyOrEqualTo`, that combines the task of checking if a Snowflake is empty and checking if that Snowflake is equal to …
> Reduce method complexity in /ban, /unban and some other commands

- src/Services/UtilityService.cs
This PR reduces method complexity in `UtilityService#CheckInteractionsAsync` by splitting the method into two parts, similar to `/ban` and `/unban`. Additionally, it converts the last `if` statement to a `return` with ternary.
After this is merged, status checks on #54 should succeed and that PR should be merged.
> Reduce method complexity of UtilityService#CheckInteractionsAsync

- .github/workflows/resharper.yml
- src/Commands/BanCommandGroup.cs
- src/Data/Options/LanguageOption.cs
- src/Responders/MessageDeletedResponder.cs
- src/Services/UtilityService.cs
Depends on #55
These changes are really small and I don't know how to reasonably split them into multiple PRs, but here's the changelog:
- The result of the `UtilityService#LogActionAsync` call in `BanCommandGroup#BanUserAsync` is no longer ignored and it's errors will now prevent feedback from being sent;
- Converted `if` statement to a `return` with ternary in `LanguageOption`;
- Slightly decreased method complexity of `MessageDeletedResponder#RespondAsync` by cleverly using Results;
- Changed the order of parameters for `UtilityService#LogActionAsync` to flow better;
- Removed the exemption for `ConvertIfToReturnStatement` for InspectCode.
> General fixes

- .github/dependabot.yml
This PR disables automatic assignation of all PRs created by Dependabot to me. There are now more people working on Boyfriend than just me. In fact, this project, in theory, can live without me as there are other members working on it.
> Do not assign Octol1ttle for Dependabot PRs

- .github/workflows/resharper.yml
- src/Commands/AboutCommandGroup.cs
- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/PingCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/InteractionResponders.cs
- src/Services/GuildUpdateService.cs
This PR uses a new feature of the InspectCode action: extensions. By adding the `Cognitive Complexity` extension, InspectCode can provide warnings and force the contributors to follow standards regarding complex methods. This functionality was previously provided by CodeFactor, but it is no longer used. Here's the full changelog of this PR:
- Allowed Actions to run on push for any branch, not just `master`;
- Added `Cognitive Complexity` plugin for InspectCode;
- Significantly reduced complexity of KickCommandGroup, MuteCommandGroup and GuildUpdateService
> Force maximum Cognitive Complexity via InspectCode

- src/Data/Options/SnowflakeOption.cs
This PR allows passing mentions as an input to SnowflakeOption by removing non-number characters from the input string.
> Remove non-numbers from SnowflakeOption inputs

- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Services/UtilityService.cs
This PR adds the `color` and `isPublic` parameters to `UtilityService#LogActionAsync`. Previously, all embeds would be sent in both public and private feedback channels with the green embed color. It is now possible to change these fields, allowing for usage of the red color in punishment commands and allowing to hide the result of `/clear` from public eyes.
> Add Color and Public parameters to LogActionAsync

- Boyfriend.csproj
- CodeAnalysis/BannedSymbols.txt
This PR adds the package `Microsoft.CodeAnalysis.BannedApiAnalyzers` to scan for banned code (defined by `CodeAnalysis/BannedSymbols.txt`) and provide warnings if it is used. The list of banned symbols is borrowed from osu! and other projects
> Add code analysis to prohibit using bad methods and properties

- src/Commands/AboutCommandGroup.cs
- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/PingCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Data/Options/BoolOption.cs
- src/Data/Options/LanguageOption.cs
- src/Data/Options/SnowflakeOption.cs
- src/Data/Options/TimeSpanOption.cs
- src/InteractionResponders.cs
- src/Responders/GuildMemberJoinedResponder.cs
- src/Responders/MessageEditedResponder.cs
- src/Services/GuildUpdateService.cs
- src/Services/UtilityService.cs
This PR removes the wrapping of in-house created result errors with `Result.FromError` (I did not know this was possible until today, lol), which reduces code verbosity and makes it easier to read, and replaces `ArgumentNullError` with `ArgumentInvalidError` when retrieving IDs from a command context, which, in my opinion, is more correct.
> Do not wrap result errors when returning them

- Boyfriend.csproj
- src/Boyfriend.cs
This PR adds the package `Serilog.Extensions.Logging.File` to add logging to file. I decided this was necessary after the bot unexpectedly went down in a tmux session, leaving no traces behind.
> Add logging to file

- src/Responders/GuildMemberJoinedResponder.cs
This PR fixes an issue where, if the `PublicFeedbackChannel` wasn't set or the welcome message was disabled, `GuildMemberJoinedResponder` would `return` early, causing roles to not be granted back if `ReturnRolesOnRejoin` was enabled, by moving the `if return` after the code that grants back roles
> Fix roles not returning on rejoin if welcome messages were disabled

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/RemindCommandGroup.cs
- src/Messages.Designer.cs
This PR closes #61.
This PR adds the `/listremind` command and the `/delremind` command. The `/delremind` command requires an index to determine which reminder to delete.
cc @mctaylors review embed design and feature experience
> Add /listremind and /delremind

- src/Data/ScheduledEventData.cs
- src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes the following bugs in ScheduledEventUpdateService:
- When a scheduled event is first added into ScheduledEventData, its status update code will be skipped. This results in some messages not being sent to the EventNotificationChannel
- When the status update code returns an unsuccessful Result, the status in ScheduledEventData will still be updated, meaning that the code will not retry.
> Scheduled event update bugfixes

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes a fatal crash that occurs when the bot tries to send an early notification for a scheduled event. An exception is thrown by `string#Format` when the argument list provided doesn't match the argument list in the template. This is fixed by correcting the template and the argument list
> Fix a crash in scheduled event early notification

- locale/Messages.tt-ru.resx
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes EventEarlyNotification timestamp not displaying correctly and also has some other changes:
- Add xmldocs for `/settingslist`'s `page` option in SettingsCommandGroup.cs
- Add option description for `index` for `/delreminder`
- Some corrections of grammatical errors in Messages.tt-ru.resx
- Fix `ArgumentOutOfRangeException` in `/settingslist` that appears if the user uses a negative integer in `page`
> EventEarlyNotification timestamp bugfix and other changes

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/RemindCommandGroup.cs
- src/Messages.Designer.cs
Without this embed, if there are no reminders created by the user, the bot will endlessly think because StringBuilder will be empty and normal embed will not be shown.
> Add failed embed for /listremind

- src/Data/ScheduledEventData.cs
- src/Responders/GuildLoadedResponder.cs
- src/Responders/ScheduledEventCreatedResponder.cs
This PR fixes an exception that would occur when deserialization of ScheduledEventData would be attempted. The exception is fixed by providing a constructor containing all properties and adding the `[JsonConstructor]` attribute.
> Add a JSON deserialization constructor for ScheduledEventData

- src/Commands/SettingsCommandGroup.cs
This PR renames commands `/settingslist` and `/settings` to `/listsettings` and `/editsettings` respectively. This helps avoid confusion and accidental use of the wrong command while conforming to a common naming style, similar to remind commands.
cc @mctaylors wiki needs updating
> Rename settings commands

- src/Commands/SettingsCommandGroup.cs
- src/Data/Options/AllOptionsEnum.cs
This PR adds autocomplete for setting keys in `/editsetting` slash command. The usage of options provided by auto-complete is enforced client-side.
Closes #97
Closes #95
> Add autocomplete for /editsettings setting keys

- src/Boyfriend.cs
- src/Services/BackgroundGuildDataSaverService.cs
- src/Services/GuildDataService.cs
This PR adds a BackgroundGuildDataSaverService which will save all guild data to disk every 5 minutes using a PeriodicTimer.
Closes #96
> Add periodic guild data saving (every 5 minutes)

- CodeAnalysis/BannedSymbols.txt
- src/Services/GuildDataService.cs
This PR fixes an issue that caused guild data JSON files to be corrupted upon saving. As it turns out `File.OpenWrite(string)` does not clear the file before writing to it. That means, if a file contains `{"MyKey": "MyValue"}` and I write `{}` to it using `File.OpenWrite(string)`, the contents of the file will be `{}MyKey": "MyValue"}`. This is a malformed JSON and will cause an error upon next bot startup.
In addition, this PR blacklists the `File.OpenWrite` method using `CodeAnalysis/BannedSymbols.txt` to prevent its accidental use in the future.
> Fix JSON corruption when saving

- src/Commands/RemindCommandGroup.cs
- src/Services/GuildDataService.cs
- src/Services/Update/MemberUpdateService.cs
This PR closes #105 
This PR fixes exceptions caused by changing a collection's contents while it is being enumerated. This can often happen with Guild- and MemberDatas. By using `ToArray()` on these global collections and using it in the `foreach` loop, we create a new copy of the collection, preventing any modification to it.
While this does introduce a lot of memory allocations, there is no fixing that. Usually, the fix to these exceptions would be to convert the `foreach` to a reverse-`for`. However, because indices cannot be used on these collections, that is not possible.
> Force enumeration of global collections before using them

- src/Commands/MuteCommandGroup.cs
- src/Data/MemberData.cs
- src/Responders/GuildMemberRolesUpdatedResponder.cs
- src/Services/Update/MemberUpdateService.cs
- Added support for `MuteRole`, now if you add any role to this setting, then try to mute a member, all his roles will be removed except for the one you set in this setting.
- Fixed `/unmute`, that tried to set target's display name to unmute reason.
> Add mute role support & fix /unmute

- src/Services/Update/MemberUpdateService.cs
If a user was muted using the `MuteRole` method and then banned, the UnknownMember warning will flood your logs when `DateTimeOffset.UtcNow > data.MutedUntil` becomes true, because there is no user in the server to unmute.
> Fix UnknownMember warning flood

- src/Services/Update/MemberUpdateService.cs
Flipping `>` to `<=` changed null handling semantics within the operator, causing the unban/unmute code to always run
> Fix auto-unban and auto-unmute always triggering

- src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes an issue that caused data of completed/cancelled scheduled events to never be collected if EventNotificationChannel wasn't set
> Don't forget to remove scheduled event data when notification channel is not set

- src/Services/Update/MemberUpdateService.cs
Apparently there are non-letter characters in between A-Z and a-z
> Correct illegal nickname characters regex

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/dependabot.yml
Issue labels have been reworked recently, causing some files in `.github` to reference non-existing issue labels. This PR updates the names of labels in these files.
> Correct issue label names per recent changes

- src/Extensions/DiffPaneModelExtensions.cs
- src/Extensions/StringExtensions.cs
This PR fixes an issue that caused syntax highlighting to be applied to incorrect lines in the message edit log. The fix is to prepend a zero-width space before every line of input text. This prevents Discord from highlighting the line when it wasn't edited
> Sanitize input text in message edit log

- src/Data/MemberData.cs
- src/Data/Reminder.cs
Closes #124 
Before we dive into this PR, let's explain a few rules of serialization and deserialization in System.Text.Json (often referred as STJ).
The important rule of serialization is that fields are ***not*** serialized unless the serializer gets passed an instance of `JsonSerializerOptions` that explicitly tells it to include fields. However, properties are serialized by default.
The important rule of ***de***serialization is that class members are only deserialized if:
1) In case of properties, they must have a setter
2) If they do not have a setter, the constructor must have an argument, required or optional, that will act as the setter for that property.
Unfortunately, both of these rules were ignored in some commit that refactored reminders. This PR is here to fix that issue …
> Fix Reminder serialization/deserialization

- src/Services/Update/ScheduledEventUpdateService.cs
- src/Services/UtilityService.cs
Closes #163 
Discord's API sucks a lot. You ask it for a member, but it won't give you a member. This is why this PR updates the `GetEventNotificationMentions` method used to determine what roles and users should get pinged for a scheduled event. Previously, the bot asked Discord to provide the member for each subscriber to determine whether or not they have the event notification role (to avoid pinging people personally when the role would already ping them). With this pull request, the bot uses MemberData, it's own member storage, for that purpose (if you're wondering why, refer to the first two sentences)
> Use MemberData to determine a subscriber's role list

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/ClearCommandGroup.cs
- src/Messages.Designer.cs
Closes #164 
This PR adds an optional argument to `/clear` - `author` of type User.
If the user is specified, only messages sent by that user will be cleared. Simple as that.
> Add filtering by message author to /clear

- src/Services/Update/ScheduledEventUpdateService.cs
This PR fixes an issue that prevented scheduled event status updates from running again if they failed. This happened because, before each update, the events would be synchronized. The `ScheduleOnStatusUpdated` field would be set even if it's already `true`, which will cause it to be set to `false` for unsuccessful updates. The issue is fixed by surrounding the field set call with a condition that will prevent setting the field from `true` to `false`
> Unschedule scheduled event status update only if last update was successful

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/RemindCommandGroup.cs
- src/Messages.Designer.cs
_There are times when you want to be sure of what you've destroyed._
Therefore, in this PR I added the output of the text of the deleted reminder along with its position in the list, because you can make a mistake with deleting a reminder and forget about what you needed to be reminded about.
> Add more info output to /delremind

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Data/GuildData.cs
- src/Messages.Designer.cs
- src/Responders/GuildLoadedResponder.cs
- src/Responders/GuildUnloadedResponder.cs
- src/Services/GuildDataService.cs
Previously, any errors in guild data load will cause the bot to be unusable in that guild. It didn't help that the end users had no information that something was wrong! Now, any errors will be logged better (with the full path to the file that couldn't be loaded), and the users will receive a message saying that functionality is degraded
The old way to save objects was to serialize them directly into streams opened by `File#Create`. This can cause problems if the serialization isn't completed, because `File#Create` overwrites the file with an empty one on the spot. Now, objects are first deserialized into a temporary file, then the original is replaced by the temporary, then the temporary is deleted.
Errors during guild data load would sometimes cause the bot to replace the corrupted …
> Handle guild data load errors better

- src/Commands/BanCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
This PR fixes an error that would appear if a string that's way too long was passed as a command argument by limiting the string's length
> Limit string argument length to avoid "embed description too long" errors

- src/Commands/AboutCommandGroup.cs
- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/PingCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Commands/ToolsCommandGroup.cs
- src/Extensions/FeedbackServiceExtensions.cs
This PR replaces usages of the `FeedbackService` implementation with the `IFeedbackService` interface. Using concrete implementations breaks the whole point of dependency injection, so it doesn't make sense to use them
> Use IFeedbackService interface instead of implementation

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Closes #184 
This PR makes issue templates less annoying by removing some unnecessary text boxes and allowing issues to be created without the use of a template.
In the Bug Report template, `Expected Behavior` and `Actual Behavior` were combined into one, and the `Known Workarounds` section was removed
In the Feature Request template, `Considered Alternatives` was also removed.
> Make issue templates less annoying

- src/Responders/MessageEditedResponder.cs
Closes #183 
In addition to the fix, now no error will be returned if the message doesn't exist in the cache as that is a (relatively) normal occurrence and isn't an indicator of an issue with the bot or its configuration
> Put edited message in cache if it's not in cache already

- docs/README.md
- src/Commands/AboutCommandGroup.cs
Old CDN links are no longer working and they must be changed to new links to display Octobot banner properly.
> Update CDN links for Octobot banner

- src/Commands/AboutCommandGroup.cs
- src/Commands/BanCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Commands/ToolsCommandGroup.cs
- src/Extensions/MarkdownExtensions.cs
- src/Extensions/StringBuilderExtensions.cs
- src/Extensions/StringExtensions.cs
In this PR, I have added StringBuilder extensions to avoid `.Append` reuse such as `.Append("- ").AppendLine()`
Closes #205
> Add StringBuilder & Markdown extensions

- Octobot.csproj
Fixes an exception that would occur when a slash command that has optional arguments would be called without them. See 
https://github.com/Remora/Remora.Discord/issues/319 for details
> Bump Remora.Commands to fix issue with optional slash command args

- src/Commands/AboutCommandGroup.cs
- src/Extensions/FeedbackServiceExtensions.cs
In this PR, I moved the repository link from the embed to a button in /about command for better UI/UX
> /about: Add repository link button

- src/Commands/AboutCommandGroup.cs
- src/Extensions/MarkdownExtensions.cs
In this PR, the behavior of the developer list display in /about has been changed. Now, if a developer is not on the same server where the /about command was executed, their username will have a link to their GitHub profile.
> /about: Show link to GitHub profile if Discord member wasn't found

- src/Commands/AboutCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Commands/ToolsCommandGroup.cs
- src/Services/Update/MemberUpdateService.cs
- src/Services/Update/SongUpdateService.cs
ReSharper inspections have been updated, causing new warnings to appear in the codebase. This time, the "Use collection expressions" inspection has been enabled for usecases where the collection is not empty. This PR fixes the check failures caused by this inspection.
> Use collection expressions in more places

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/AboutCommandGroup.cs
In this PR, I made it so that in the Author field instead of the hardcoded name was the name of the Discord bot. This was done to match the icon next to it in the same field.
Replaces #224
> /about: Show Discord bot username instead of hardcoded one

- src/Commands/BanCommandGroup.cs
- src/Commands/ClearCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Octobot.cs
- src/Responders/GuildLoadedResponder.cs
- src/Services/GuildDataService.cs
- src/Services/Update/MemberUpdateService.cs
- src/Services/Update/ScheduledEventUpdateService.cs
- src/Services/Utility.cs
Originally, these classes were services because I thought that all DI-resolvable classes need to be services. However, this is not true, so we can make these classes (notably Utility and GuildDataService) not extend anything. `UtilityService` was renamed to `Utility` for simplicity
> Remove "extends IHostedService" from classes where it's not required

- src/Octobot.cs
- src/Services/Profiler/Profiler.cs
- src/Services/Profiler/ProfilerEvent.cs
- src/Services/Profiler/ProfilerFactory.cs
This PR adds the base classes required for profiling code inside of Octobot. The implementation of the profiler is similar to Minecraft, however it is more detailed and provides per-event logs for each event. This PR does not change any code to be profiled and this is intentional. Changes required for profiling will come as separate PRs, one for commands, one for responders, and one for background services.
> Add profiler base

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/ToolsCommandGroup.cs
- src/Data/MemberData.cs
- src/Messages.Designer.cs
- src/Responders/GuildMemberJoinedResponder.cs
Closes #241 
Updates:
- Show if the user was kicked by [adding "Kicked" parameter to MemberData](https://github.com/LabsDevelopment/Octobot/issues/241)
- Change `mctaylors-ru`'s `UserInfoBannedPermanently` string to be different from `UserInfoBanned`
- Finally add `AppendPunishmentsInformation` method to avoid Cognitive Complexity
- Use MemberData to check if the user was banned
- Rename variable `isMuted` to `wasMuted` to be consistent with other variable names
> /userinfo: Show if the user was kicked w/ updates

- CodeAnalysis/BannedSymbols.txt
Using Thread.Sleep blocks the _entire_ thread from doing *anything*, while Task.Delay allows the thread to execute other tasks while the delay is passing. The inability to cancel Thread.Sleep may also cause longer shutdowns
tl;dr Thread.Sleep bad, Task.Delay good
made because of https://github.com/LabsDevelopment/Octobot/pull/234/commits/578c03871de0dd042f2fe0918df296f0a8123e00
> Ban usages of Thread#Sleep

- src/Extensions/LoggerExtensions.cs
Fixes an issue on Windows that would cause the `ResultErrorMessage` to be unindented.
> Fix newline in LogResult

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/BanCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/RemindCommandGroup.cs
- src/Commands/ToolsCommandGroup.cs
- src/Messages.Designer.cs
This PR was made to help users who are trying /remind for the first time by showing an example of the correct time format in the description to avoid this:
> Add time format example to the description of commands that use TimeSpan.

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Messages.Designer.cs
- src/Responders/GuildLoadedResponder.cs
If you go through the locales, sooner or later you will notice `Sound*`, which is used in `GuildLoadedResponder.cs`. A new contributor (most likely) will not understand what it is used for at once, because we use `$"Loaded{i}".Localized()` instead of `Messages.Sound*` directly. Also, if you change the locale's value, for example the same "Loaded!", `Sound` will not fit anymore, because "Loaded!" is not a sound, but a phrase.
Other suggestions are welcome.
> Rename locale Sound to Loaded for clarity

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/BuildInfo.cs
- src/Commands/AboutCommandGroup.cs
- src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
- src/Messages.Designer.cs
- src/Responders/GuildLoadedResponder.cs
In this PR, I'm disabling the Report Issue button if a "dirty" version is detected. This is done just in case so that "smart" developers don't accidentally report a bug that they themselves created.
> Disable issue report button if dirty version detected

- src/Responders/MessageDeletedResponder.cs
- src/Responders/MessageEditedResponder.cs
This will better align with how a normal moderator would respond to the log:
Before: "see log" -> "jump to message without knowing what changed" -> "read message diff"
After: "see log" -> "read message diff" -> "jump to message for context"
In addition, the change improves consistency with how reminders are shown.
> Change position of "Jump to ..." action for better consistency

- src/BuildInfo.cs
GitInfo's `RepositoryUrl` string depends on origin URL, which is unvalidated user input that isn't even guaranteed to exist. This can cause [issues that are almost impossible to debug](https://github.com/TeamOctolings/Octobot/issues/281)
Closes #281
> fix: do not use RepositoryUrl from GitInfo

- src/Extensions/LoggerExtensions.cs
In LoggerExtensions#LogResult we skip logging the result if the error is "user or environment error". What matches that criteria is defined by Remora's implementation:
```csharp
public static bool IsUserOrEnvironmentError(this IResultError error)
{
return error
is CommandNotFoundError
or AmbiguousCommandInvocationError
or RequiredParameterValueMissingError
or ParameterParsingError
or ConditionNotSatisfiedError;
}
```
However, none of these errors should *ever* happen or be ignored:
* CommandNotFoundError: The client shouldn't send us non-existing commands. This *can* happen because the client's command list can get out of sync with the server's, but this happens rarely.
* AmbiguousCommandInvocationError: We don't have commands that would trigger this error
* …
> Do not use ResultError#IsUserOrEnvironmentError

- locale/Messages.resx
- locale/Messages.ru.resx
- locale/Messages.tt-ru.resx
- src/Commands/BanCommandGroup.cs
- src/Commands/KickCommandGroup.cs
- src/Commands/MuteCommandGroup.cs
- src/Commands/SettingsCommandGroup.cs
- src/Data/GuildSettings.cs
- src/Data/Options/AllOptionsEnum.cs
- src/Octobot.cs
- src/Services/AccessControlService.cs
- src/Services/Update/MemberUpdateService.cs
- src/Services/Utility.cs
Octobot has various moderation commands such as /ban, /mute, /kick. These commands add multiple features to Discord's built-in functions (such as durations and logging). Some admins may want to force their users to use Octobot's commands instead of Discord UI functions. However, due to the current design, they can't take away the permissions as that remove access to the respective command.
This PR adds the `ModeratorRole` option which allows anyone who has `ManageMessages` permission and the role to perform any moderator action.
If the role is not set, the Discord permissions are checked instead. If the user doesn't have the role, but has the permission, they can still run the command.
> Add 'ModeratorRole' guild setting

- src/Commands/AboutCommandGroup.cs
- src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
- src/Responders/GuildLoadedResponder.cs
- src/Services/Update/ScheduledEventUpdateService.cs
This change was made to avoid using emoji in the code, which may not render correctly depending on the IDE and/or operating system.
> Use unicode codes instead of emojis

- src/Commands/AboutCommandGroup.cs
PR's name speaks for itself. It might also be useful to update the logo more easily.
> Make the logo in /about independent of image hosting

- src/BuildInfo.cs
- src/Commands/AboutCommandGroup.cs
In this PR, I made the logo link in /about use HEAD instead of hardcoded branch.
> Don't hardcode logo's link in /about

- .github/dependabot.yml
This PR *should* disable creating Dependabot PRs for patch updates. These updates often don't contain significant changes and only clutter the PR feed in addition to taking the maintainers' time
> Dependabot: ignore patch updates

- src/Extensions/ResultExtensions.cs
Originally I did not enable because "stack traces are expensive to retrieve", but let's be honest, who cares, this is a Discord bot, there's no such thing as "good performance"
> Enable result stacktraces in release mode

- TeamOctolings.Octobot/TeamOctolings.Octobot.csproj
Changing the project name ended up changing the names of the assemblies, which is a significant breaking change which caused our CD to fail
> Change assembly name back to "Octobot"

- TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
- TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
who tf thought that putting 1234915912 methods responsible for 23981 commands in a single class was a good idea???????
> Separate /*info commands from ToolsCommandGroup

- TeamOctolings.Octobot/Commands/AboutCommandGroup.cs
- TeamOctolings.Octobot/Commands/BanCommandGroup.cs
- TeamOctolings.Octobot/Commands/ClearCommandGroup.cs
- TeamOctolings.Octobot/Commands/Events/ErrorLoggingPostExecutionEvent.cs
- TeamOctolings.Octobot/Commands/Events/LoggingPreparationErrorEvent.cs
- TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
- TeamOctolings.Octobot/Commands/KickCommandGroup.cs
- TeamOctolings.Octobot/Commands/MuteCommandGroup.cs
- TeamOctolings.Octobot/Commands/PingCommandGroup.cs
- TeamOctolings.Octobot/Commands/RemindCommandGroup.cs
- TeamOctolings.Octobot/Commands/SettingsCommandGroup.cs
- TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
- TeamOctolings.Octobot/Responders/GuildLoadedResponder.cs
- TeamOctolings.Octobot/Responders/GuildMemberJoinedResponder.cs
- TeamOctolings.Octobot/Responders/GuildMemberLeftResponder.cs
- TeamOctolings.Octobot/Responders/GuildUnloadedResponder.cs
- TeamOctolings.Octobot/Responders/MessageDeletedResponder.cs
- TeamOctolings.Octobot/Responders/MessageEditedResponder.cs
- TeamOctolings.Octobot/Responders/MessageReceivedResponder.cs
Apparently the `[UsedImplicitly]` annotation suppresses the "Class has no inheritors and can be marked sealed" warning. Cool to know.
> Seal implicitly used classes

- TeamOctolings.Octobot/Services/AccessControlService.cs
Closes #311 
This change fixes unexpected behavior when a member's Discord roles get desynchronized with their MemberData roles (e.g. when a member gets role-muted). In addition this results in less API requests being made when there are cache misses (commands should execute faster)
> Use MemberData roles when checking permissions & interactions

- TeamOctolings.Octobot/Responders/MessageDeletedResponder.cs
In order to determine who deleted a message, Octobot fetches the audit log with a filter on the action "Message Delete", gets the latest entry and uses its author if the timestamps roughly match. However, if the filter returns no entries (as in, no message deletions are present in the audit log), `Single()` will throw an exception with the message `Sequence contains no elements`. To fix this, this PR replaces `Single()` with `SingleOrDefault()` and adds a null-check on `auditLog` in the form of a pattern access
> Handle audit log entries for message deletion being empty

- TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
- TeamOctolings.Octobot/Commands/MuteCommandGroup.cs
- TeamOctolings.Octobot/Commands/RemindCommandGroup.cs
- TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
- TeamOctolings.Octobot/Responders/GuildLoadedResponder.cs
- TeamOctolings.Octobot/Responders/GuildMemberJoinedResponder.cs
- TeamOctolings.Octobot/Services/GuildDataService.cs
- TeamOctolings.Octobot/Services/Update/MemberUpdateService.cs
- TeamOctolings.Octobot/Services/Update/ScheduledEventUpdateService.cs
- TeamOctolings.Octobot/Utility.cs
This PR makes sure that a cancellation token is never *required* to use an `async` method. This does not affect user experience in any way, only code quality.
> Always default cancellation tokens

- TeamOctolings.Octobot/Commands/SettingsCommandGroup.cs
- TeamOctolings.Octobot/Data/Options/BoolOption.cs
- TeamOctolings.Octobot/Data/Options/GuildOption.cs
- TeamOctolings.Octobot/Data/Options/IGuildOption.cs
- TeamOctolings.Octobot/Data/Options/LanguageOption.cs
- TeamOctolings.Octobot/Data/Options/TimeSpanOption.cs
- TeamOctolings.Octobot/Messages.Designer.cs
- TeamOctolings.Octobot/Messages.resx
- TeamOctolings.Octobot/Messages.ru.resx
> Show an error when entering the same value from the settings

- TeamOctolings.Octobot/Extensions/LoggerExtensions.cs
- TeamOctolings.Octobot/Extensions/ResultExtensions.cs
This PR fixes an issue where the `LogResultStackTrace` method would log stack traces for results that encountered an error due to a cancelled operation/task. The `LoggerExtensions` class already skipped `TaskCanceledException`s, but didn't skip `OperationCanceledException`s (which is a parent of `TaskCanceledException`).
The patch specifically does not affect *inner* results which are canceled. Skipping logging these could hide the true cause of an error which appears important
> Don't log stack traces for cancelled operations

- TeamOctolings.Octobot/BuildInfo.cs
- TeamOctolings.Octobot/Commands/AboutCommandGroup.cs
- TeamOctolings.Octobot/Messages.Designer.cs
- TeamOctolings.Octobot/Messages.resx
- TeamOctolings.Octobot/Messages.ru.resx
A some sort of UX change. Repository link will be still accessible from the website.
> /about: Replace repo link with website link

- .github/workflows/build-push.yml
Fixes current deployment failure due to use of non-standard SSH port on our production host.
`ssh-keyscan` command was moved out to its own step to help troubleshooting in the future.
> Retrieve SSH port from environment secrets

- .github/dependabot.yml
- TeamOctolings.Octobot/TeamOctolings.Octobot.csproj
This pull request downgrades GitInfo from 3.5.0 to 3.3.5 due to a decision from the maintainers to lock features behind a paywall.
> Downgrade GitInfo from 3.5.0 to 3.3.5

- TeamOctolings.Octobot/Extensions/GuildScheduledEventExtensions.cs
- TeamOctolings.Octobot/Services/GuildDataService.cs
This PR fixes catastrophic guild data loading errors that appear when there are lingering temporary files. In normal operation, temporary files are deleted as soon as they are copied to the main file. It is also expected that temporary files are valid JSON files.
However, due to a yesterday's DoS attack, something:tm: happened and a bunch of empty temporary files got written to disk. When Octobot recovered from the attack, it was unable to load any guild data because of the temporary files.
This PR addresses this issue by changing the data loading logic:
1) Check if there's a temporary file. If it exists, try loading it.
2) If it is successfully loaded, move the temp file to the main file and resume operation as normal
3) If it could not be loaded, try loading the main file
4) If it is …
> Handle temporary files being present when loading guild data
